/*1/ PARA CADA DEPARTAMENTO MOSTRAR EL NUMERO, NOMBRE,EL IMPORTE TOTAL DE LA NOMINAS QUE HAY QUE PAGAR POR SUS EMPLEADOS*/

/*2MOSTRAR EL NOMBRE Y LA LOCALIDAD DEL  DEPARTAMETNO AL QUE PERTENECE EL EMPLEADO QUE MAS SALARIO TIENE*/

SELECT DNOMBRE,LOC
FROM DEPART WHERE DEPT_NO IN(
SELECT DEPT_NO FROM EMPLE
WHERE SALARIO=(SELECT MAX(SALARIO)
FROM EMPLE));
/*LISTAR EL NUMERO DE EMPLEADOS Y APELLIDOS DE LOS EMPLEADOS DEL DEPARTAMENTO EN SEVILLA*/
SELECT EMP_NO,APELLIDO
FROM EMPLE WHERE DEPT_NO=(
SELECT DEPT_NO FROM
DEPART WHERE LOC='SEVILLA');
/*4AUMENTAR EL SALARIO EN UN 3%A AQUELLOS EMPLEADOS CUYA NOMINA SEA INFERIOR A 2000€*/
UPDATE EMPLE
SET SALARIO=(SALARIO*0.03)+SALARIO
WHERE (SALARIO+NVL(COMISION,0))<2000;
/*5MOSTRAR PARA CADA LIBRO SU CODIGO,TITULO, AUTORY CANTIDAD DE UNIDADES PRESTADAS Y DISPONIBLES*/
SELECT L.COD_LIBRO,L.TITULO,L.AUTOR,COUNT(P.COD_LIBRO) "UNIDADES
PRESTADAS", (L.UNIDADES-(COUNT(P.COD_LIBRO))) "UNIDADES DISPONIBLES"
FROM LIBROS L, PRESTAMOS P
WHERE L.COD_LIBRO = P.COD_LIBRO(+)
GROUP BY P.COD_LIBRO,L.COD_LIBRO,L.TITULO,L.AUTOR,L.UNIDADES;

/*SI UN LIBRO HA DE SER DEVUELTO EN UN MAXIMO DE 15 DIAS Y CONSIDERANDO QUE LA FECHA DE HOY FUERA 26/02/2012, ESCRIBIR LAS SQLS DE LAS PREGUNTAS 6 Y 7*/

/*6 MOSTRAR LA LISTA DE LIBROS DE YA ESTAN FUERA D EPLAZO*/
SELECT *
FROM LIBROS
WHERE COD_LIBRO IN (SELECT COD_LIBRO FROM PRESTAMOS WHERE
TO_DATE('26/02/2012')-FECHA_PRESTAMOS>15);

/*7MOSTRAR TAMBIEN QUIEN LOS TIENE Y CUANTO TENDRA QUE PAGAR DE MULTA A RAZON DE 2EUROS POR DIA D ERETRASO.LA COLUMNA 
CON EL IMPORTE TENDRA EL TITULO DE COLUMNA "IMPORTE MULTA"*/
SELECT L.*,P.FECHA_PRESTAMOS,S.*,TO_CHAR(((TO_DATE('26/02/2012')-
(FECHA_PRESTAMOS+15))*2),'9,999L')"IMPORTE MULTA €"
FROM LIBROS L, PRESTAMOS P, SOCIOS S
WHERE L.COD_LIBRO = P.COD_LIBRO AND (TO_DATE('26/02/2012')-
FECHA_PRESTAMOS)>15
AND S.COD_SOCIO = P.COD_SOCIO;

/*8REALIZAR UN PRESTAMO DE LIBRO "PUESTA A PUNTO DE ORACLE" AL SOCIO JAVIER SANCHEZ CON CODIGO DE SOCIO 223.EL PRESTAMO
SE REALIZARA CON FECHA DE HOY*/
INSERT INTO PRESTAMOS
VALUES(223,(SELECT COD_LIBRO FROM LIBROS WHERE UPPER(TITULO)='PUESTA A
PUNTO DE ORACLE'), SYSDATE);


/*9BORRAR LOS PRESTAMOS REALIZADOS POR LOS SOCIOS DE MADRID*/
DELETE FROM PRESTAMOS
WHERE COD_SOCIO IN (SELECT COD_SOCIO FROM SOCIOS WHERE
UPPER(PROVINCIA)='MADRID');


/*CREAR UNA VISTA PARA MOSTRAR LOS DATOS D E LOS SOCIOS(CODIGO,NOMBRE Y PROVINCIA) JUNTO CON LOS DATOS DE LOS LIBROS QUE TIENE PRESTADOS
(CODIGO,TITULO Y TEMA).NO S EPODRAN MODIFICAR LOS DATOS DE LAS TABLAS DESDE ESTA VISTA.LOS DATOS APARECEN ORDENADOS POR CODIGO DE SOCIO*/
CREATE VIEW VISTA1
(CODIGO_SOCIO,NOMBRE,PROVINCIA,CODIGO_LIBROS,TITULO,TEMA)
AS SELECT S.COD_SOCIO,S.NOMBRE,S.PROVINCIA,P.COD_LIBRO,L.TITULO,L.TEMA
FROM SOCIOS S, PRESTAMOS P, LIBROS L
WHERE S.COD_SOCIO = P.COD_SOCIO
AND P.COD_LIBRO = L.COD_LIBRO
ORDER BY S.COD_SOCIO
WITH READ ONLY;



