create table alumno01.PRODUCTOS
(
ID_FAB VARCHAR2 (3) NOT NULL,
ID_PRODUCTO VARCHAR2 (5) NOT NULL,
DESCRIPCION VARCHAR2 (25) NOT NULL,
PRECIO NUMBER (6,2) NOT NULL,
EXISTENCIAS NUMBER (4) DEFAULT 0,
CONSTRAINT productos_clave_pk PRIMARY KEY (ID_FAB,ID_PRODUCTO),
CONSTRAINT productos_precio_ck CHECK (PRECIO>0)

);