/*agrupacion de elemento pag87*/

/*CONTAR NUMERO DE EMPLEADOS DE CADA DEPARTAMENTP*/
SELECT DEPT_NO "NUMERO DEPARTAMENTO",COUNT(*)"Nº DE EMPLEADOS"
FROM EMPLE
GROUP BY DEPT_NO ;

/*CUANTOS EMPLEADOS TENGO DE CADA  OFICIO*/
SELECT OFICIO,COUNT(*)"POR OFICIO"
FROM EMPLE
GROUP BY OFICIO;



SELECT DEPT_NO "DEPARTAMENTO",TO_CHAR(ROUND (AVG(SALARIO),2),'B9,999.99L')"MEDIA SALARIO"
FROM EMPLE
GROUP BY DEPT_NO;

/*SELECCIONAMOS CUANTOS EMPLEADOS HAY DE CADA OFICIO EN EL DEPARTAMENTO 20*/
SELECT OFICIO,COUNT(*)
FROM EMPLE
WHERE DEPT_NO=20
GROUP BY OFICIO;

/*MEDIA DEL SALARIO DEL DEPARTAMENTO 20 AGRUPADOS POR OFICIO*/

SELECT OFICIO, AVG(SALARIO)"MEDIA"
FROM EMPLE
WHERE DEPT_NO=20/*CONDICION SOBRE LA TABLA*/
GROUP BY OFICIO
HAVING AVG (SALARIO)>3000;/*CONDICION SOBRE EL GRUPO*/

/*PAGINA91*/
/*VISUALIZAR EN LA TABLA EMPLE TODOS LOS DEPARTAMENTOS EJER 3*/
SELECT DEPT_NO,COUNT(*)
FROM EMPLE
GROUP BY DEPT_NO
HAVING COUNT(*)>4;

/*VISUALIZAR EL LISTADO ANTERIOS DESCENDENTEMENTE*/

SELECT DEPT_NO"DEPARTAMENTO",COUNT(*)
FROM EMPLE
GROUP BY DEPT_NO
HAVING COUNT(*)>4
ORDER BY COUNT(*) DESC;

/*PAG93 OBTENER LA SUMA DE SALARIOS, EL SALARIO MAXIMO*/
SELECT DEPT_NO,TO_CHAR(SUM(SALARIO),'B99,999L'), TO_CHAR(MAX(SALARIO),'B99,999L'),TO_CHAR(MIN(SALARIO),'B99,999L')
FROM EMPLE
GROUP BY DEPT_NO;


/*CUAL ES EL NUMERO DE EMPLEADOS DEL DEPARTAMENTO*/
SELECT MAX(COUNT(*))
FROM EMPLE GROUP BY DEPT _NO


/*OBTENER EL NUMERO DE EMPLEADOS POR DEPARTAMENTO QUE COBRAN MAS DE 1500*/
SELECT DEPT_NO,COUNT(*)
FROM EMPLE
GROUP BY DEPT_NO
HAVING COUNT>1500;
/*ULTIMU EJERCICIU DE LA PAGINA*/
SELECT DEPT_NO,COUNT(*)
FROM EMPLE
WHERE SALARIO>1500
GROUP BY DEPT_NO;

/*ACTIVIDADES 4 BLOQUE2*/
/*DADA LA TABLA EMPLE, OBTENER EL SUELDO MEDIO EL NUMERO DE COMISIONES NO NULAS, EL MAXIMO SUELDO*/

SELECT ROUND (AVG(SALARIO),2),MAX(SALARIO),MIN(SALARIO),COUNT(COMISION)
FROM EMPLE
WHERE DEPT_NO=30;

/*4 CONTAR LAS FILAS*/
SELECT COUNT(*)
FROM LIBRERIA
WHERE TEMA LIKE'%A%';

/*6*/
SELECT DISTINCT COUNT(ESTANTE)"Nº ESTANTES DIFERENTES" FROM LIBRERIA;


