/*TEMA 4 ACTIVIDADES BLOQUEII*/
    /*EJERICCIO 1*/
SELECT ABS(146) FROM DUAL;
SELECT ABS(-30) FROM DUAL;
SELECT CEIL(-2.3) FROM DUAL;
SELECT CEIL(-2) FROM DUAL;
SELECT POWER(10,0) FROM DUAL;
    /*EJERCICIO 3*/
SELECT TO_CHAR(AVG(SALARIO+NVL(COMISION,0)),'B99,999.99L')"SUELDO MEDIO", COUNT(COMISION) "COMISIONES NO NULAS", 
    TO_CHAR(MAX(SALARIO+NVL(COMISION,0)),'B99,999.99L') "SUELDO MAXIMO",TO_CHAR(MIN(SALARIO+NVL(COMISION,0)),'B99,999.99L') "SUELDO MINIMO"
FROM EMPLE
WHERE DEPT_NO=30;
    /*EJERCICIO 8*/
SELECT RPAD(RTRIM(LTRIM(TITULO,'"'),'".'),47,'-^') AS "RESULTADO"
FROM MISTEXTOS; 
    /*EJERCICIO 9*/
SELECT LOWER(RTRIM(LTRIM(TITULO,'"'),'".'))
FROM MISTEXTOS;
/*IMPORTANTE*/

    /*EL TITULO UNA VEZ ELIMINADO LAS COMILLAS QUE LE QUEDEN LAS PALABRAS EN FORMATO TITULO CON LA PRIMERA LETRA EN MAYUSCULAS LA DEMAS EN MINUSCULAS*/
SELECT INITCAP(RTRIM(LTRIM(TITULO,'"'),'".'))
FROM MISTEXTOS;
    /*EJERCICIO 10*/
SELECT SUBSTR(AUTOR,INSTR(AUTOR,',')+2) AS "NOMBRE",SUBSTR(AUTOR,1,INSTR(AUTOR,',')-1) AS "APELLIDOS"
FROM LIBROS;
    /*A PARTIR DE LA TABLA NACIMIENTOS QUE APAREZCA EL NOMBRE Y LA EDAD*/
SELECT NOMBRE,FECHANAC "FECHA NACIMIENTO", (EXTRACT(YEAR FROM SYSDATE )-EXTRACT(YEAR FROM FECHANAC)) AS "EDAD",
TRUNC(MONTHS_BETWEEN(SYSDATE,FECHANAC)/12)"EDAD 1",
TRUNC((SYSDATE-FECHANAC)/365) AS "EDAD MEJOR" 
FROM NACIMIENTOS;
    /*EJERCICIO 15*/
SELECT TEMA, LENGTH(RTRIM(TEMA)) "LONGITUD", SUBSTR(TEMA,LENGTH(RTRIM(TEMA)),1) "CARACTER FINAL"
FROM LIBRERIA
ORDER BY TEMA;
    /*EJERCICIO 17*/
SELECT TO_DATE('01051998'), TO_CHAR(TO_DATE('01051998'), 'MONTH') FROM DUAL;
    /*ejercicio18 noooooooooooooooooooooooooooooooooo(DECODE)*/
    /*EJERCICIO 19+ LOS EMPLEADOS LES DAN UNA GRATIFICACION DEL 5% DEL SUELDO*/
SELECT APELLIDO, SALARIO,TO_CHAR(SALARIO*0.05,'999.99L') "GRATIFICACION SALARIAL",TO_CHAR((SALARIO+SALARIO*0.05),'9999.99L')"TOTAL SALARIO" 
FROM EMPLE
WHERE TRUNC((SYSDATE-FECHA_ALT)/365)>19;