/*EXAMEN DE CONSULTES*/
/*MOSTRAR APELLIDO Y SALARIO DE ('VENDEDOR'TABLA OFICIO) CUYO SALARIO ESTE
ENTRE 2000 Y 3000*/
SELECT APELLIDO,SALARIO
FROM EMPLE
WHERE OFICIO LIKE'VENDEDOR' AND SALARIO BETWEEN 2000 AND 3000
ORDER BY APELLIDO;
/*INTRODUCE POR TECLADO...*/
ACCEPT Vsal PROMPT 'INTRODUCE EL SALARIO';
SELECT *
FROM EMPLE
WHERE SALARIO>&Vsal;
/*LISTAR EL NOMBRE DE LOS EMPLEADOS QUE EMPIECEN POR A*/
SELECT *
FROM EMPLE
WHERE APELLIDO LIKE'_A%';
/*MOSTRAR NUMERO DE EMPLEADO Y LA NOMINA(SALARIO+COMISION)*/
SELECT EMP_NO AS "NUMERO EMPLEADO", APELLIDO AS "NOMBRE EMPLEADO", OFICIO, DIR, 
FECHA_ALT, TO_CHAR(SALARIO,'999,999.99L')AS "SALARIO" , TO_CHAR(NVL(COMISION,0),'999,999L')"COMISION",TO_CHAR((SALARIO+NVL(COMISION,0)),'999,999.99L')AS"NOMINA",DEPT_NO
FROM EMPLE;
/*EJERCICIO 5*/
SELECT DEPT_NO,COUNT(APELLIDO) "EMPLEADOS POR DEPARTAMENTO"
FROM EMPLE
WHERE UPPER(OFICIO)='EMPLEADO'
GROUP BY DEPT_NO
ORDER BY DEPT_NO;