/*2*/
SELECT APELLIDO
FROM EMPLE
WHERE APELLIDO LIKE'A%';


/*3*/
SELECT TO_CHAR(AVG(SALARIO+COMISION),'B99,999.9L')AS"SUELDO",COUNT(COMISION)AS "NUMERO COMISIONES",MAX(SALARIO+COMISION)AS "SALARIO MAXIMO",MIN(SALARIO+COMISION)AS "SALARIO MINIMO"
FROM EMPLE
WHERE DEPT_NO=30;

/*8*/
SELECT RPAD( RTRIM(LTRIM(TITULO,'"'),'".'),47,'-^')AS "RESULTADO"
FROM MISTEXTOS;
/*SACAR EDAD Y NOMBRE*/
SELECT NOMBRE,EXTRACT(YEAR FROM SYSDATE)-EXTRACT(YEAR FROM FECHANAC)
FROM NACIMIENTOS;
/*OTRA FORMA*/
SELECT NOMBRE,TO_CHAR(SYSDATE,'YYYY')-TO_CHAR(FECHANAC,'YYYY')AS"EDAD"
FROM NACIMIENTOS;
/*OTRA FORMA*/
SELECT TRUNC(MONTHS_BETWEEN(SYSDATE,FECHANAC)/12)AS "EDAD"
FROM NACIMIENTOS;
/*LAFORMA BUENA*/
SELECT TRUNC((SYSDATE-FECHANAC)/365)AS EDAD
FROM NACIMIENTOS;
/*15*/
SELECT TEMA,LENGTH(TEMA)/*LOS ESPACIOS EN BLANCO SON CARACTERES ASIQUE EL LEGHT CUENTALOS*/
FROM LIBRERIA;
/*OTRA FORMA*/
SELECT TEMA,LENGTH(RTRIM(TEMA)),SUBSTR(TEMA,LENGTH(RTRIM(TEMA)),1)/*QUITA ESPACIOS EN BLANCO*/
FROM LIBRERIA
ORDER BY TEMA;
/*17*/
SELECT TO_DATE('01051998','DD/MM/YYYY')AS "FECHA",EXTRACT(MONTH FROM TO_DATE('01051998','DD/MM/YYYY'))
FROM DUAL;
/*OTRA FORMA*/
SELECT TO_DATE('01051998','DD/MM/YYYY')AS "FECHA",TO_CHAR(TO_DATE('01051998','DD/MM/YYYY'),'MONTH')
FROM DUAL;
/*19*/

SELECT SYSDATE FROM DUAL;

SELECT ADD_MONTHS(SYSDATE,5)
FROM DUAL

SELECT NEXT_DAY(SYSDATE,'MARTES')
FROM DUAL

Select TRUNC(((sysdate-FECHA_ALT)/365),2)from EMPLE;


SELECT SYSDATE FROM DUAL;
SELECT ADD_MONTHS(SYSDATE,5)FROM DUAL;
SELECT LAST_DAY(SYSDATE)FROM DUAL;
SELECT NEXT_DAY(SYSDATE,'DOMINGO')FROM DUAL;

SELECT TO_DATE(05051998,'DD/MM/YYYY')FROM DUAL;

SELECT  COUNT(DEPT_NO),DEPT_NO
FROM EMPLE
GROUP BY DEPT_NO;

SELECT COUNT(EMP_NO),DEPT_NO
FROM EMPLE
WHERE SALARIO>2000 AND SALARIO<5500
GROUP BY DEPT_NO HAVING DEPT_NO IN(30);

SELECT TO_CHAR(SALARIO,'B99,999.9L')
FROM EMPLE
