/*ejercicios pag5*/
SELECT*
FROM EMPLE
WHERE DEPT_NO IN(10,30);

SELECT*
FROM EMPLE
WHERE DEPT_NO IN (10,30);

SELECT * FROM EMPLE WHERE DEPT_NO NOT IN(10,30);

/*FALTEN ALGUNES POL MEDIO*/

SELECT* FROM EMPLE WHERE SALARIO BETWEEN 1000 AND 2000;

SELECT* FROM EMPLE WHERE SALARIO NOT BETWEEN 1000 AND 2000;

SELECT APELLIDO,SALARIO,DEPT_NO FROM EMPLE WHERE SALARIO>2000 AND DEPT_NO IN (20,30);

