/*1-OBTENER ORDENADOS ALFABETICAMENTE LOS NOMBRES Y SALARIOS DE LOS EMPLEADOS DE OFICIO VENDEDOR
Y CON UN SALARIO ENTRE 2000 Y 3000*/
SELECT APELLIDO, SALARIO
FROM EMPLE
WHERE OFICIO='VENDEDOR' AND SALARIO BETWEEN 2000 AND 3000
ORDER BY APELLIDO;
 

/*2-OBTENER UNLISTADO CON LA INFORMACION DE LOS EMPLEADOS QUE TENGAN UN SALARIO 
MAYOR QUE UN VALOR QUE SE INTRODUCIRA POR TECLADO*/
ACCEPT VALOR PROMPT 'INTRODUCE SALARIO'
SELECT *
FROM EMPLE
WHERE SALARIO>=&VALOR;


/*3-LISTADO DE LOS EMPLEADOS CUYO APELLIDO TENGA UNA A EN SEGUNDA POSICION*/
SELECT *
FROM EMPLE
WHERE APELLIDO LIKE '_A%';


/*4-LISTADO DE LOS EMPLEADOS CON SU NOMINA(SALARIIO+COMISION.LAS COLUMNAS DEBERAN APARECER DEBIDAMENTE TITULADAS.
LA NOMINA APARECERA CON EL FORMATO INDICADO, EL PUNTO PARA LOS DECIMALES, LA COMA PARA LOS MILES Y EL SIMBOLO DE MONEDA*/
SELECT APELLIDO,TO_CHAR((SALARIO+NVL(COMISION,0)),'999,999.9L')AS "NOMINA"
FROM EMPLE;


/*5-A PARTIR DE LA TABLA EMPLES, VISUALIZAR EL NMUMERO DE EMPLEADOS DE CADA DEPARTAMENTO CUYO OFICIO SEA EMPLEADO*/
SELECT DEPT_NO,COUNT(APELLIDO)AS "Nº DE EMPLEADOS"
FROM EMPLE
WHERE OFICIO='EMPLEADO'
GROUP BY DEPT_NO;


/*6-BUSCAR LOS DEPARTAMENTOS QUE TIENEN MAS DE UNA PERSONA TRABAJADO  EN LA MISMA PROFESION*/
SELECT DEPT_NO,OFICIO,COUNT(APELLIDO)
FROM EMPLE
GROUP BY DEPT_NO,OFICIO HAVING COUNT(APELLIDO)>=1;


/*7-BUSCAR EL MAXIMO Y EL MINIMO DE SUELDO DE CADA DEPARTAMENTO. EL VALOR APARECERA CON FORMATO DE COMA
PARA LOS MILES Y EL SIMBOLO DE MONEDA*/
SELECT DEPT_NO,TO_CHAR(MAX(SALARIO),'999,999.9L')AS "SALARIO MAXIMO",TO_CHAR(MIN(SALARIO),'999,999.9L')AS"SALARIO MINIMO"
FROM EMPLE
GROUP BY DEPT_NO;


/*8-MOSTRAR PARA CADA DEPARTAMENTO EL NUMERO DE AÑOS COMPLETOS QUE LLEVA TRABAJANDO EL EMPLEADO CON MAS ANTIGUEDAD*/
SELECT DEPT_NO,MAX(TRUNC((SYSDATE-FECHA_ALT)/365))AS "AÑOS"
FROM EMPLE
GROUP BY DEPT_NO;



/*9-OBTENER LOS EMPLEADOS CUYO AÑO DE FECHA DE ALTA SEA MAYOR QUE 1981*/
SELECT *
FROM EMPLE
WHERE EXTRACT(YEAR FROM FECHA_ALT)>1981;


/*10-OBTENER UN LISTADO DONDE APAREZCA EL SALARIO ACTUAL Y EL SALARIO CON UNA SUBIDA DEL5% PARA LOS EMPLEADOS DEL DEPARTAMENTO 20
 QUE GANA MENOS DE 1500.EL LISTADO DEBERA APARECER DEBIDAMENTE FORMATEADO*/
 SELECT APELLIDO, TO_CHAR(SALARIO,'999,999.9L')AS "SALARIO",TO_CHAR((SALARIO*1.05),'999,999.9L')AS "SALRIO+5%"
 FROM EMPLE
 WHERE DEPT_NO =20; 
 
 /*11 APARTIR DE LA TABLA LIBROS MOSTRAR EN UNA COLUMNA EL NOMBRE DEL AUTOR Y EN OTRA SUS APELLIDOS*/
 SELECT  SUBSTR(AUTOR,INSTR(AUTOR,',')+1)AS "NOMBRE",SUBSTR(AUTOR,0,INSTR(AUTOR,',')-1)AS "APELLIDO"
 FROM LIBROS;
 
 
 /*12A PARTIR DE LA TABLA LIBROS MOSTRAR EN UNA COLUMNA EL NOMBRE DEL AUTOR Y SUS APELLIDOS EN ESE ORDEN. LA COLUMNA APARECERA
 CON EL TITULO"NOMBRE Y APELLIDOS" ADEMAS EL NOMBRE Y LOS APELLIDOS DEBERAN APARECER EN MINUSCULAS CON LA PRIMERA LETRA DE CADA PALABRA
 EN MAYUSCULAS */
 SELECT CONCAT(CONCAT(INITCAP(SUBSTR(AUTOR,INSTR(AUTOR,',')+1)),' '),INITCAP(SUBSTR(AUTOR,0,INSTR(AUTOR,',')-1)))AS" NOMBRE COMPLETO"
 FROM LIBROS;
