ALTER TABLE EMPLE
ADD CONSTRAINT emple_pk PRIMARY KEY (EMP_NO);

ALTER TABLE DEPART
ADD CONSTRAINT depart_pk PRIMARY KEY (DEPT_NO);

ALTER TABLE EMPLE
ADD CONSTRAINT emple_dir_fk FOREIGN KEY(DIR)
REFERENCES EMPLE (EMP_NO) ON DELETE SET NULL;

ALTER TABLE EMPLE
ADD CONSTRAINT emple_depto_fk FOREIGN KEY (DEPT_NO)
REFERENCES DEPART (DEPT_NO) ON DELETE SET NULL;


