SELECT *
FROM EMPLE;

SELECT APELLIDO, OFICIO
FROM EMPLE;

SELECT DISTINCT OFICIO
FROM EMPLE;

SELECT APELLIDO, OFICIO
FROM EMPLE 
WHERE OFICIO='VENDEDOR';

SELECT APELLIDO, OFICIO
FROM EMPLE 
WHERE OFICIO='DIRECTOR';

SELECT APELLIDO, OFICIO, SALARIO
FROM EMPLE
WHERE SALARIO>=2000;

SELECT APELLIDO, OFICIO, SALARIO
FROM EMPLE
WHERE SALARIO<=2500;

SELECT APELLIDO, OFICIO, DEPT_NO
FROM EMPLE
WHERE DEPT_NO=10;

SELECT APELLIDO, OFICIO, SALARIO, DEPT_NO
FROM EMPLE
WHERE DEPT_NO=10 AND SALARIO>2000;

SELECT APELLIDO, OFICIO, SALARIO, DEPT_NO
FROM EMPLE
WHERE DEPT_NO=20 OR SALARIO>2000;

SELECT APELLIDO, OFICIO, SALARIO, DEPT_NO
FROM EMPLE
WHERE SALARIO<2000 
ORDER BY SALARIO;

SELECT APELLIDO, OFICIO, SALARIO, DEPT_NO
FROM EMPLE
WHERE SALARIO<2000 
ORDER BY SALARIO ASC;

SELECT APELLIDO, OFICIO, SALARIO, DEPT_NO
FROM EMPLE
WHERE SALARIO<2000 
ORDER BY SALARIO DESC;

SELECT APELLIDO, OFICIO, SALARIO, DEPT_NO
FROM EMPLE
ORDER BY SALARIO DESC ;

SELECT APELLIDO, OFICIO, SALARIO, DEPT_NO
FROM EMPLE
ORDER BY SALARIO DESC, APELLIDO DESC;

SELECT DEPT_NO AS "NUMERO DEPARTAMENTO",DNOMBRE "NOMBRE DE DEPARTAMENTO"
FROM DEPART;

/* SELECIONA TODAS LAS COLUMNAS DE LA TABLA EMPLE QUE EL NUMERO DE DEPARTAMENTO SEA 20 */
SELECT *
FROM EMPLE
WHERE DEPT_NO=20;

/* SELECIONA TODAS LAS COLUMNAS DE LA TABLA EMPLE QUE EL NUMERO DE DEPARTAMENTO SEA 20 
Y ORDENADOS POR APELLIDO */
SELECT *
FROM EMPLE
WHERE DEPT_NO=20
ORDER BY APELLIDO;

/* SELECIONA LAS COLUMNAS DESCRITAS DE LA TABLA EMPLE QUE EL NUMERO DE DEPARTAMENTO SEA 20 
Y ORDENADOS POR APELLIDO */
SELECT EMP_NO, APELLIDO, OFICIO, DEPT_NO
FROM EMPLE
WHERE DEPT_NO=20
ORDER BY APELLIDO;

/* SELECIONA LAS COLUMNAS DESCRITAS CON SU ALIAS DE LA TABLA EMPLE QUE EL NUMERO DE DEPARTAMENTO SEA 20 
Y ORDENADOS POR APELLIDO */
SELECT EMP_NO AS "NUMERO EMPLEADO", APELLIDO AS "NOMBRE", OFICIO AS "PUESTO DE TRABAJO", DEPT_NO AS "NUM_DPTO" 
FROM EMPLE
WHERE DEPT_NO=20
ORDER BY APELLIDO;

/* TABLA EMPLEADOS CON OFICIO ANALISTA CON LOS VALORES
 DE LA BASE DE DATOS PASE A MAYUSCULAS */
SELECT *
FROM EMPLE
WHERE UPPER(OFICIO)='ANALISTA';

/* IDEM PERO ORDENADOS POR EL NUMEMPLEADO Y EL PASO A MINUSCULAS */
SELECT *
FROM EMPLE
WHERE LOWER(OFICIO)='analista'
ORDER BY EMP_NO;

SELECT *
FROM EMPLE
WHERE DEPT_NO=20 AND UPPER(OFICIO)='VENDEDOR';

/*realizar una consulta de todos los empleados ordenado
descendentemente por el puesto que ocupan y dentro de un mismo
puesto deberán de aparecer ordenados descendentemente por el
nombre*/
SELECT *
FROM EMPLE
ORDER BY OFICIO DESC, APELLIDO DESC;

/*Consultar cuales son los distintos tipos de Puestos que tienen los
empleados*/
SELECT OFICIO
FROM EMPLE;

/*Consultar cuales son los distintos tipos de Puestos que tienen los
empleados*//*Solo sale una vez*/
SELECT DISTINCT OFICIO
FROM EMPLE;

/*introduces por teclado el valor que quieras 
introduciendolo todo en minusculas para el oficio con apostrofes */
SELECT *
FROM EMPLE
WHERE LOWER(OFICIO)='&pOFICIO';

/*introduces por teclado el valor que quieras 
introduciendolo todo en minusculas para oficio con apostrofes 
y numero departamento sin apostrofes*/
SELECT *
FROM EMPLE
WHERE LOWER(OFICIO)='&pOFICIO' AND DEPT_NO=&pDEP;

/*CON VISUALIZACION DE MENSAJES
introduces por teclado el valor que quieras 
introduciendolo todo en minusculas para oficio con apostrofes 
y numero departamento sin apostrofes*/
ACCEPT VOFICIO PROMPT 'INTRODUCE EL OFICIO'; 
ACCEPT VDEP PROMPT 'INTRODUCE EL DEPARTAMENTO'; 
SELECT *
FROM EMPLE
WHERE LOWER(OFICIO)='&VOFICIO' AND DEPT_NO=&VDEP;

/*Contabilizar el número de empleados que hay en un departamento
y de un oficio que se introducen por teclado, utilizando para ello la
expresión COUNT(*) en la parte de la sentencia SELECT que
muestra las columnas*/
ACCEPT pOFICIO PROMPT 'INTRODUCE EL OFICIO'; 
ACCEPT pDEP PROMPT 'INTRODUCE EL NUMERO DE DEPARTAMENTO';
SELECT COUNT(*)/*AS*/"Total de empleados"
FROM EMPLE
WHERE UPPER(OFICIO)='&pOFICIO' AND DEPT_NO= &pDEP;

/*SUBIR SUELDO A EMPLEADOS*/
SELECT APELLIDO, SALARIO /*AS*/ "Salario actual", SALARIO*1.2/*AS*/ "Salario nuevo"
FROM EMPLE;

/*SUBIR SUELDO A EMPLEADOS Y VISUALIZAR LOS QUE COBREN DE SALARIO NUEVO >2000 */
SELECT APELLIDO, SALARIO /*AS*/ "Salario actual", SALARIO*1.2/*AS*/ "Salario nuevo"
FROM EMPLE
WHERE SALARIO*1.2>=2000;

/*BUSCAR POR UN SITIO*/
SELECT *
FROM EMPLE
WHERE APELLIDO LIKE 'A%';

/*PRIMERA LETRA 'A' DESPUES LO QUE SEA*/
SELECT *
FROM EMPLE
WHERE APELLIDO NOT LIKE 'A%';

/*PRIMERA LO QUE SEA SEGUNDA LETRA 'A' DESPUES LO QUE SEA*/
SELECT *
FROM EMPLE
WHERE APELLIDO LIKE '_A%';

/*TERMINAN EN A*/
SELECT *
FROM EMPLE
WHERE APELLIDO LIKE '%A';

SELECT *
FROM EMPLE
WHERE OFICIO LIKE UPPER ('Director');

SELECT *
FROM EMPLE
WHERE APELLIDO LIKE 'M%';

SELECT *
FROM EMPLE
WHERE APELLIDO LIKE '%X%';

SELECT *
FROM EMPLE
WHERE APELLIDO LIKE '__M';

SELECT *
FROM EMPLE
WHERE APELLIDO LIKE 'N_%';

/*ejercicios operadores pag33*/
SELECT APELLIDO, SALARIO
FROM EMPLE
WHERE SALARIO>1500
ORDER BY SALARIO DESC;

SELECT APELLIDO, COMISION
FROM EMPLE
WHERE COMISION !=0;

SELECT APELLIDO, COMISION
FROM EMPLE
WHERE (COMISION IS NOT NULL) AND (COMISION>0);

SELECT APELLIDO
FROM EMPLE
WHERE APELLIDO LIKE'J%';

SELECT *
FROM EMPLE
WHERE (APELLIDO LIKE 'J%') OR (APELLIDO LIKE 'S%');

SELECT *
FROM EMPLE
WHERE APELLIDO LIKE '_A%';

/*PROBLEMA QUE LOS QUE NO TIENEN COMISION NO APARECEN EN NOMINA*/
SELECT EMP_NO, APELLIDO, OFICIO, SALARIO, COMISION, (SALARIO + COMISION) "NOMINA"
FROM EMPLE;

/*SOLUCIONADO PONIENDO VALOR 0 A LOS QUE SALEN NULL*/
SELECT EMP_NO, APELLIDO, OFICIO, SALARIO, COMISION, (SALARIO + NVL(COMISION , 0)) "NOMINA"
FROM EMPLE;

/*ORDENADO POR NOMINA*/
SELECT EMP_NO, APELLIDO, OFICIO, SALARIO, NVL(COMISION , 0), (SALARIO + NVL(COMISION , 0)) "NOMINA"
FROM EMPLE
ORDER BY NOMINA;

/*EJERCICIOS PAG 35*/
SELECT APELLIDO, DEPT_NO
FROM EMPLE
WHERE DEPT_NO IN(10,30);

SELECT APELLIDO, DEPT_NO
FROM EMPLE
WHERE DEPT_NO NOT IN(10,30);

SELECT APELLIDO, OFICIO
FROM EMPLE
WHERE OFICIO IN('ANALISTA', 'EMPLEADO','VENDEDOR');

SELECT APELLIDO, OFICIO
FROM EMPLE
WHERE OFICIO NOT IN('ANALISTA', 'EMPLEADO','VENDEDOR');

SELECT APELLIDO, SALARIO
FROM EMPLE
WHERE SALARIO BETWEEN 1000 AND 2000;

SELECT APELLIDO, SALARIO
FROM EMPLE
WHERE SALARIO NOT BETWEEN 1000 AND 2000;

SELECT APELLIDO, SALARIO, DEPT_NO
FROM EMPLE
WHERE SALARIO>2000 AND DEPT_NO IN (10,20);

/*probando funciones de la tabla DUAL (ya la tiene por defecto, es de pruebas) */
/*VALOR ABSOLUTO*/
SELECT ABS(-2) FROM DUAL;
/*VALOR ENTERO INMEDIATAMENTE SUPERIOR O IGUAL*/
SELECT CEIL(-2) FROM DUAL;
SELECT CEIL(-2.5) FROM DUAL;
/*VALOR ENTERO INMEDIATAMENTE INFERIOR O IGUAL*/
SELECT FLOOR(-2) FROM DUAL;
SELECT FLOOR(-2.5) FROM DUAL;
/*CALCULA LA POTENCIA DE UN NUMERO*/
SELECT POWER(3,5) FROM DUAL;
/*REDONDEAR UN NUMERO AL NUMERO DE DECIMALES*/
SELECT ROUND(2.5365,3) FROM DUAL;
/*RAIZ CUADRADA*/
SELECT SQRT(25) FROM DUAL;
/*RESTO*/
SELECT MOD(20,4) FROM DUAL;
/*MEDIA ARITMETICA DE UN CONJUNTO DE VALORES*/
/*EJERCICIOS PAGINA 59*/
/*AVERAGE*//*1*/SELECT AVG(SALARIO) FROM EMPLE;
/*2*/
SELECT AVG(SALARIO) 
FROM EMPLE 
WHERE DEPT_NO=10;
/*3*/
SELECT COUNT(*) FROM EMPLE;
/*4 HECHO POR MI*/
SELECT (COUNT(*)-COUNT(COMISION)) FROM EMPLE;
/*4 COMO DEBERIA SER*/
SELECT COUNT(*) 
FROM EMPLE
WHERE COMISION IS NULL;
/*5*/
SELECT MAX(SALARIO) FROM EMPLE;
/*6 Y 7, SON SUBCONSULTAS*/
/*8*/
SELECT SUM(SALARIO+NVL(COMISION,0))"TOTAL NOMINA"
FROM EMPLE;
/*9*/
SELECT COUNT(DISTINCT OFICIO)"OFICIOS DIFERENTES"
FROM EMPLE;
/*10*/
SELECT COUNT(DISTINCT OFICIO) AS "OFICIOS EN 10 Y 20"
FROM EMPLE
WHERE DEPT_NO=10 OR DEPT_NO=20;
/*COJE EL VALOR MAS ALTO Y EL MAS BAJO*/
SELECT GREATEST('benito', 'jorge', 'isabel')FROM DUAL;
SELECT LEAST('benito', 'jorge', 'isabel')FROM DUAL;
/*PROBAR PAG 63*/
SELECT CHR(65),CHR(66),CHR(67),CHR(69),CHR(106),CHR(268) FROM DUAL;
/*CONCATENACION*/ 
SELECT CONCAT(' HOLA',' PEPE') FROM DUAL;
/**/
SELECT LPAD('pepe',50,' .-. ') FROM DUAL;
SELECT RPAD('pepe',50,' .-. ') FROM DUAL;

/*QUITA ESPACIOS EN BLANCO*/
SELECT LTRIM('PPPPPEEPIN','PE') FROM DUAL;
SELECT LTRIM('        PEPIN') FROM DUAL;

/*REEMPLAZAR CADENA DE CARACTERES*/
SELECT REPLACE('Hola pepin necesito hablar contigo','pepin') from dual;
SELECT REPLACE('Hola pepin necesito hablar contigo','pepin','juanin') from dual;

/*SUBSTRAER*/
SELECT SUBSTR('HOLA SOY HECTOR',3,8)FROM DUAL;
SELECT SUBSTR('HOLA SOY HECTOR',1,10)FROM DUAL;

/*FUNCIONES DE FECHAS*/
SELECT SYSDATE FROM DUAL;
SELECT ADD_MONTHS(SYSDATE,2) FROM DUAL;
SELECT ADD_MONTHS(SYSDATE,-2) FROM DUAL;
SELECT LAST_DAY(SYSDATE) FROM DUAL;
SELECT MONTHS_BETWEEN(SYSDATE,'04-06-2015') FROM DUAL;
SELECT MONTHS_BETWEEN(SYSDATE,'05-12-1993')/12 FROM DUAL;
SELECT NEXT_DAY(SYSDATE,'LUNES') FROM DUAL;
SELECT EXTRACT(MONTH FROM SYSDATE) FROM DUAL;
    /*CONVERSIONES FECHAS*/
    SELECT TO_CHAR(SYSDATE,'DD') FROM DUAL;
    SELECT TO_CHAR(SYSDATE,'SSSSS')/3600 FROM DUAL;
    SELECT TO_CHAR(SYSDATE,'YEAR') FROM DUAL;
    SELECT TO_CHAR(SYSDATE,'"HOY ESTAMOS A "DD" DE " MM" DE "YYYY') FROM DUAL;
/*FUNCIONES CONVERSION*/
SELECT SALARIO FROM EMPLE;
    /*0 IZQUIERDA, LA COMA SON LOS MILES, EL PUNTO DECIMALES Y LA L LA MONEDA*/
SELECT TO_CHAR(SALARIO,'B9,999.99L')FROM EMPLE;
SELECT TO_CHAR(SALARIO,'RN')FROM EMPLE;
/*MOSTRAR USUARIO*/
SHOW USER;
/*TEMA 4 ACTIVIDADES BLOQUE II*/
SELECT ABS(146) FROM DUAL;
SELECT ABS(-30) FROM DUAL;
SELECT CEIL(-2.3)FROM DUAL;
SELECT CEIL(-2)FROM DUAL;
SELECT POWER(10,0) FROM DUAL;
SELECT ROUND(33.67) FROM DUAL;
SELECT ROUND(-33.67,2) FROM DUAL;
SELECT ROUND(-33.27,1) FROM DUAL;
SELECT CEIL(2) FROM DUAL;
SELECT CEIL(1.3) FROM DUAL;
SELECT FLOOR(1.3) FROM DUAL;
SELECT TRUNC(67.232) FROM DUAL;
SELECT TRUNC(67.232,2) FROM DUAL;
    /*2*/
    SELECT COUNT(APELLIDO)"EMPLEADOS QUE EMPIEZAN POR A"
    FROM EMPLE
    WHERE APELLIDO LIKE 'A%';
    /*3*/
    
/*FALTAN EJERCICIOS*/

/*en la tabla emple visualizar por cada oficio de los empleados del departamento 30 la suma de los salarios*/
SELECT OFICIO, TO_CHAR(SUM(SALARIO),'B9,999.9L') "SALARIO TOTAL"
FROM EMPLE
WHERE DEPT_NO=30
GROUP BY OFICIO;

/*A PARTIR DE LA TABLA EMPLE VISUALIZAR EL NUMERO DE EMPLEADOS DE CADA DEPARTAMENTO CUYO OFICIO ES EMPLEADO*/    
SELECT COUNT(OFICIO) NUMERO_DE_EMPLEADOS, DEPT_NO "NUMERO DEPARTAMENTO"
FROM EMPLE
WHERE OFICIO='EMPLEADO'
GROUP BY DEPT_NO;

/*MOSTRAR LOS DEPARTAMENTOS QUE TIENEN MAS DE DOS PERSONAS TRABAJANDO EN EL MISMO OFICIO*/
SELECT DEPT_NO "NUMERO DEPARTAMENTO", OFICIO, COUNT(*) "Nº EMPLE"
FROM EMPLE
GROUP BY DEPT_NO, OFICIO
HAVING COUNT(*)>1;

/*DADA LA TABLA LIBRERIA MOSTRAR POR CADA ESTANTE CUANTOS EJEMPLARES TIENE*/
SELECT ESTANTE, SUM(NUM_EJEMPLARES)"NUMERO EJEMPLARES"
FROM LIBRERIA
GROUP BY ESTANTE
ORDER BY ESTANTE;

/*DADA LA TABLA LIBRERIA VISUALIZAR POR CADA ESTANTE EL TOTAL DE EJEMPLARES DE CADA TEMA*/
SELECT ESTANTE, TEMA, SUM(NUM_EJEMPLARES)"NUMERO EJEMPLARES"
FROM LIBRERIA
GROUP BY ESTANTE, TEMA
ORDER BY ESTANTE;

/*DADA LA TABLA LIBRERIA MOSTRAR O AVERIGUAR CUANTOS TEMAS TIENE CADA ESTANTE */
SELECT ESTANTE, COUNT(TEMA) NUMERO_TEMAS
FROM LIBRERIA
GROUP BY ESTANTE
ORDER BY ESTANTE;

/*MOSTRAR LOS ESTANTES QUE TENGAN 3 TEMAS*/
SELECT ESTANTE, COUNT(TEMA) NUMERO_TEMAS
FROM LIBRERIA
GROUP BY ESTANTE
HAVING COUNT(TEMA)=3
ORDER BY ESTANTE;

/*en la tabla emple visualizar por cada oficio de los empleados del departamento VENTAS la suma de los salarios*/
SELECT OFICIO, TO_CHAR(SUM(SALARIO),'B9,999.9L') "SALARIO TOTAL"
FROM EMPLE
WHERE DEPT_NO=(SELECT DEPT_NO
FROM DEPART
WHERE DNOMBRE='VENTAS')
GROUP BY OFICIO;

/*PAG 39 EJERCICIOS UT 4*/
/*1*/
SELECT APELLIDO, OFICIO, DEPT_NO
FROM EMPLE
WHERE OFICIO=(SELECT OFICIO FROM EMPLE WHERE APELLIDO='SALA'/*O APELLIDO LIKE 'SALA'*/);
/*2*/
SELECT APELLIDO, OFICIO, DEPT_NO
FROM EMPLE
WHERE DEPT_NO IN (SELECT DEPT_NO FROM DEPART WHERE LOC LIKE 'MADRID' OR LOC LIKE 'BARCELONA');

SELECT APELLIDO, OFICIO, DEPT_NO
FROM EMPLE
WHERE DEPT_NO IN (SELECT DEPT_NO FROM DEPART WHERE LOC IN('MADRID','BARCELONA'));

/*3*/
SELECT APELLIDO, OFICIO, SALARIO, DEPT_NO
FROM EMPLE
WHERE OFICIO IN(SELECT OFICIO FROM EMPLE WHERE APELLIDO LIKE 'FERNANDEZ') 
    AND SALARIO IN (SELECT SALARIO FROM EMPLE WHERE APELLIDO LIKE 'FERNANDEZ');

/*4*/
SELECT APELLIDO, OFICIO, DEPT_NO
FROM EMPLE
WHERE OFICIO IN(SELECT OFICIO FROM EMPLE WHERE APELLIDO LIKE 'MARTIN') 
    AND SALARIO BETWEEN 1000 AND 2000;
    
/*5*/
SELECT APELLIDO, DEPT_NO
FROM EMPLE
WHERE DEPT_NO IN(SELECT DEPT_NO FROM EMPLE WHERE APELLIDO='SALA' OR APELLIDO='GIL');

/*SUBCONSULTAS CORRELACIONADAS*/
SELECT E.*, (SELECT TO_CHAR(AVG(SALARIO),'B9,999.9L')FROM EMPLE WHERE DEPT_NO=E.DEPT_NO) MEDIA_POR_DEPARTAMENTO
FROM EMPLE E
WHERE SALARIO>(SELECT AVG(SALARIO)FROM EMPLE WHERE DEPT_NO=E.DEPT_NO);

/*TEMA 4 ACTIVIDADES BLOQUEII*/ 
/*EJERCICIO 5*/
SELECT TEMA
FROM LIBRERIA
WHERE NUM_EJEMPLARES IN (SELECT MAX(NUM_EJEMPLARES) FROM LIBRERIA WHERE UPPER(TEMA) LIKE '%E%' ) AND UPPER(TEMA) LIKE '%E%';

/*EJERCICIO 6*/
SELECT DISTINCT ESTANTE
FROM LIBRERIA
ORDER BY ESTANTE;

/*EJERCICIOS SUBCONSULTAS*/ 
    /*OBTENER UN LISTADO DE TODOS LOS EMPLEADOS CUYO DEPARTAMENTO SEA VENTAS*/
SELECT *
FROM EMPLE
WHERE DEPT_NO IN (SELECT DEPT_NO FROM DEPART WHERE UPPER(DNOMBRE)='VENTAS');

    /*OBTENER UN LISTADO DE TODOS LOS EMPLEADOS QUE SEAN DEL DEPARTAMENTO DE VENTAS Y DEL DEPARTAMENTO CONTABILIDAD*/
SELECT *
FROM EMPLE
WHERE DEPT_NO IN (SELECT DEPT_NO FROM DEPART WHERE UPPER(DNOMBRE)='VENTAS' OR  UPPER(DNOMBRE)='CONTABILIDAD');

    /*OBTENER LOS EMPLEADOS DEL DEPARTAMENTO DE VENTAS Y CUYA NOMINA SEA MAYOR QUE 2000 EUROS*/
SELECT EMPLE.*, SALARIO+NVL(COMISION,0) AS "NOMINA"
FROM EMPLE
WHERE DEPT_NO IN (SELECT DEPT_NO FROM DEPART WHERE UPPER(DNOMBRE)='VENTAS') AND (SALARIO+NVL(COMISION,0))>2000; 

    /*INDICAR LOS NOMBRES DE LOS DEPARTAMENTOS DE AQUELLOS EMPLEADOS CUYA COMISION ES IGUAL A NULL*/
SELECT DNOMBRE
FROM DEPART
WHERE DEPT_NO IN (SELECT DEPT_NO FROM EMPLE WHERE COMISION IS NULL);

    /*INDICAR LOS NOMBRES DE LOS DEPARTAMENTOS QUE NO TENGAN NINGUN EMPLEADO*/
SELECT DNOMBRE
FROM DEPART
WHERE DEPT_NO NOT IN(SELECT DISTINCT DEPT_NO FROM EMPLE);

    /*VISUALIZAR LOS TEMAS CON MAYOR NUMERO DE EJEMPLARES DE LA TABLA LIBRERIA Y
     QUE TENGAN AL MENOS UNA 'E' (PUEDE SER UN TEMA O VARIOS)*/
SELECT TEMA 
FROM LIBRERIA
WHERE NUM_EJEMPLARES IN (SELECT MAX(NUM_EJEMPLARES)FROM LIBRERIA WHERE UPPER(TEMA) LIKE '%E%') AND UPPER(TEMA) LIKE '%E%';

    /*VISUALIZAR APELLIDO, EL SALARIO Y EL NUMERO DE DEPARTAMENTO DE AQUELLOS 
    EMPLEADOS DE LA TABLA EMPLE CUYO SALARIO SEA EL MAYOR DE SU DEPARTAMENTO*/
SELECT E.APELLIDO,E.SALARIO, E.DEPT_NO
FROM EMPLE E
WHERE SALARIO = (SELECT MAX(SALARIO) FROM EMPLE WHERE DEPT_NO=E.DEPT_NO);

    /*A PARTIR DE LA TABLA EMPLE, VISUALIZAR EL NUMERO DE VENDEDORES DEL DEPARTAMENTO VENTAS*/
SELECT COUNT(*) "NUMERO DE VENDEDORES"
FROM EMPLE
WHERE UPPER(OFICIO)='VENDEDOR' AND DEPT_NO= (SELECT DEPT_NO FROM DEPART WHERE UPPER(DNOMBRE)='VENTAS');

    /*PARTIENDO DE LA TABLA EMPLE, VISUALIZAR POR CADA OFICIO DE LOS EMPLEADOS 
    DEL DEPARTAMENTO VENTAS LA SUMA DE SALARIOS*/
SELECT OFICIO, TO_CHAR(SUM(SALARIO),'9,999.9L') "TOTAL SALARIOS"
FROM EMPLE
WHERE DEPT_NO=(SELECT DEPT_NO FROM DEPART WHERE UPPER(DNOMBRE)='VENTAS')
GROUP BY OFICIO;

    /*DESDE LA TABLA EMPLE, VISUALIZAR EL DEPARTAMENTO QUE TENGA 
    MAS EMPLEADOS CUYO OFICIO SEA EMPLEADO*/
SELECT DEPT_NO
FROM EMPLE 
WHERE OFICIO='EMPLEADO'
GROUP BY DEPT_NO
HAVING COUNT(*)=(SELECT MAX(COUNT(APELLIDO)) FROM EMPLE WHERE OFICIO='EMPLEADO' GROUP BY DEPT_NO);

    /*SELECIONAR AQUELLOS APELLIDOS DE LA TABLA EMPLE CUYO SALARIO 
    SEA MAYOR O IGUAL A LA MEDIA DE SU SALARIO EN SU DEPARTAMENTO*/
SELECT APELLIDO, SALARIO
FROM EMPLE E
WHERE SALARIO>=(SELECT AVG(SALARIO)FROM EMPLE WHERE DEPT_NO=E.DEPT_NO);





