/*PAGINA 39 SUBCONSULTAS*/

SELECT APELLIDO,OFICIO,DEPT_NO
FROM EMPLE
WHERE OFICIO IN(SELECT OFICIO FROM EMPLE WHERE APELLIDO LIKE'SALA');

SELECT APELLIDO,OFICIO,DEPT_NO
FROM EMPLE
WHERE DEPT_NO IN(SELECT DEPT_NO FROM DEPART WHERE LOC LIKE 'MADRID' OR LOC LIKE 'BARCELONA')

SELECT APELLIDO,OFICIO,SALARIO,DEPT_NO 
FROM EMPLE
WHERE OFICIO=(SELECT OFICIO FROM EMPLE WHERE APELLIDO='FERNANDEZ')  AND SALARIO=(SELECT SALARIO FROM EMPLE WHERE APELLIDO LIKE 'FERNANDEZ')

SELECT APELLIDO,OFICIO,DEPT_NO
FROM EMPLE
WHERE SALARIO BETWEEN 1200 AND 2000 AND OFICIO=(SELECT OFICIO FROM EMPLE WHERE APELLIDO='MARTIN');

SELECT APELLIDO
FROM EMPLE
WHERE DEPT_NO IN(SELECT DEPT_NO FROM EMPLE WHERE APELLIDO='GIL' OR APELLIDO='SALA');


/*actividad tema 4 actividades bloque II EJERCICIO 5*/

SELECT TEMA
FROM LIBRERIA
WHERE 

