/*SUBCONSULTAS*/
/*OBTENER UN ISTADO DE TODOS LOS EMPLEADOS CUYO DEPARTAMENTO ES VENTAS*/
SELECT *
FROM EMPLE
WHERE DEPT_NO=(SELECT DEPT_NO FROM DEPART WHERE DNOMBRE='VENTAS');

/*OBTENER UN LISTADO DE TODOS LOS EMPLEADOS QUE SEAN DEL DEPARTAMENTO VENTAS Y EL DEPARTAMENTO CONTABILIDAD*/
SELECT*
FROM EMPLE
WHERE DEPT_NO IN(SELECT DEPT_NO FROM DEPART WHERE DNOMBRE='VENTAS' OR DNOMBRE='CONTABILIDAD');

/*OBTENER LOS EMPLEADOS DEL DEPARTAMENTO VENTAS Y CUYA NOMINA SEA MAYOR  QUE 2000*/
SELECT E.*,(SALARIO+NVL(COMISION,0)) AS "NOMINA"
FROM EMPLE E
WHERE(SALARIO+NVL(COMISION,0))>2000 AND DEPT_NO=(SELECT DEPT_NO FROM DEPART
WHERE UPPER(DNOMBRE)='VENTAS');


/*SI PONGO * Y DEPUES PONGO ALGUNA COLUMNA TENGO QUE HACER UNA CUALIFICACION,PONIENDO UN
ALIAS E.*  */


/*INDICAR LOS NOMBRE DE LOS DEPARTAMENTOS DE AQUELLOS EMPLEADOS CUYA COMISION ES IGUAL A NULL*/
SELECT DNOMBRE FROM DEPART
WHERE DEPT_NO IN( SELECT DEPT_NO FROM EMPLE
WHERE COMISION IS NULL);


/*INDICAR LOS NOMBRES DE LOS DEPARTAMENTOS QUE NO TENGAN NINGUN EMPLEADO*/
SELECT DNOMBRE FROM DEPART
WHERE DEPT_NO NOT IN(
SELECT DISTINCT DEPT_NO FROM EMPLE);

/*6*/


/*7 LO DE USUARIO U4 NO FACEY CASU*/
SELECT  APELLIDO,E.SALARIO,E.DEPT_NO FROM EMPLE E
WHERE E.SALARIO IN(
SELECT MAX(SALARIO)
FROM EMPLE
WHERE DEPT_NO= E.DEPT_NO);

/*8*/
SELECT COUNT(*)
FROM EMPLE
WHERE OFICIO='VENDEDOR' AND DEPT_NO=(SELECT DEPT_NO
FROM DEPART
WHERE DNOMBRE='VENTAS');
/*9*/
SELECT OFICIO,SUM(SALARIO)
FROM EMPLE
WHERE DEPT_NO=
(SELECT DEPT_NO
FROM DEPART
WHERE DNOMBRE='VENTAS')
GROUP BY OFICIO;
/*10*/
SELECT DEPT_NO
FROM EMPLE
WHERE OFICIO='EMPLEADO'
GROUP BY DEPT_NO
HAVING COUNT(*)=(SELECT MAX(COUNT(EMP_NO))
FROM EMPLE
WHERE OFICIO='EMPLEADO'
GROUP BY DEPT_NO)

/*-BLOQUE3*/
/*4 SELECCIONAR AQUELLOS APELLIDOS DE LA TABLA EMPLE CUYO SALARIO SEA MAYOR*/
SELECT APELLIDO FROM EMPLE
WHERE SALARIO>='250'







