
DROP TABLE DEPART CASCADE CONSTRAINTS;

CREATE TABLE DEPART ( DEPT_NO NUMBER(2) NOT NULL, DNOMBRE VARCHAR2(14 BYTE), LOC VARCHAR2(14 BYTE) ) 
TABLESPACE USERS LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING;


DROP TABLE EMPLE CASCADE CONSTRAINTS;

CREATE TABLE EMPLE ( 
  EMP_NO NUMBER(4) NOT NULL, 
  APELLIDO VARCHAR2(10 BYTE), 
  OFICIO VARCHAR2(10 BYTE), 
  DIR NUMBER(4), 
  FECHA_ALT DATE, 
  SALARIO NUMBER(10), 
  COMISION NUMBER(10), 
  DEPT_NO NUMBER(2) NOT NULL 
) TABLESPACE USERS LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING;


DROP TABLE LIBRERIA CASCADE CONSTRAINTS;

CREATE TABLE LIBRERIA ( 
  TEMA VARCHAR2(15 BYTE) NOT NULL, 
  ESTANTE VARCHAR2(1 BYTE), 
  num_ejemplares NUMBER(2) 
) 
TABLESPACE USERS LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING;


DROP TABLE ALUMNOS CASCADE CONSTRAINTS;

CREATE TABLE ALUMNOS ( DNI VARCHAR2(10 BYTE) NOT NULL, 
  APENOM VARCHAR2(30 BYTE), 
  DIREC VARCHAR2(30 BYTE),  
  POBLA VARCHAR2(15 BYTE), 
  TELEF VARCHAR2(10 BYTE) ) TABLESPACE USERS LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING;


DROP TABLE ASIGNATURAS CASCADE CONSTRAINTS;

CREATE TABLE ASIGNATURAS ( 
   COD NUMBER(2) NOT NULL, 
   NOMBRE VARCHAR2(50 BYTE) 
) TABLESPACE USERS LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING;


DROP TABLE NOTAS CASCADE CONSTRAINTS;

CREATE TABLE NOTAS ( 
	DNI VARCHAR2(10 BYTE) NOT NULL, 
	COD NUMBER(2) NOT NULL, 
	NOTA NUMBER(2)
) TABLESPACE USERS LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING;



Insert into ALUMNOS
   (DNI, APENOM, DIREC, POBLA, TELEF)
 Values
   ('12344345', 'Alcalde García, Elena', 'C/Las Matas,24', 'Madrid', '917766545');
Insert into ALUMNOS
   (DNI, APENOM, DIREC, POBLA, TELEF)
 Values
   ('4448242', 'Cerrato Vela, Luis', 'C/Mina 28 - 3A', 'Madrid', '916566545');
Insert into ALUMNOS
   (DNI, APENOM, DIREC, POBLA, TELEF)
 Values
   ('56882942', 'Díaz Fernández, María', 'C/Luis Vives 25', 'MOstoles', '915577545');
COMMIT;

Insert into ASIGNATURAS
   (COD, NOMBRE)
 Values
   (1, 'PROGRAMACION LENGUAJES ESTRUCTURADOS');
Insert into ASIGNATURAS
   (COD, NOMBRE)
 Values
   (2, 'SISTEMAS INFORMATICOS');
Insert into ASIGNATURAS
   (COD, NOMBRE)
 Values
   (3, 'ANALISIS DE APLICACIONES');
Insert into ASIGNATURAS
   (COD, NOMBRE)
 Values
   (4, 'FOL');
Insert into ASIGNATURAS
   (COD, NOMBRE)
 Values
   (5, 'RET');
Insert into ASIGNATURAS
   (COD, NOMBRE)
 Values
   (6, 'ENTORNOS GRAFICOS');
Insert into ASIGNATURAS
   (COD, NOMBRE)
 Values
   (7, 'HERRAMIENTAS CASE');
Insert into ASIGNATURAS
   (COD, NOMBRE)
 Values
   (8, 'FCT');

COMMIT;

Insert into DEPART
   (DEPT_NO, DNOMBRE, LOC)
 Values
   (10, 'CONTABILIDAD', 'SEVILLA');
Insert into DEPART
   (DEPT_NO, DNOMBRE, LOC)
 Values
   (20, 'INVESTIGACION', 'MADRID');
Insert into DEPART
   (DEPT_NO, DNOMBRE, LOC)
 Values
   (30, 'VENTAS', 'BARCELONA');
Insert into DEPART
   (DEPT_NO, DNOMBRE, LOC)
 Values
   (40, 'PRODUCCION', 'BILBAO');
COMMIT;

Insert into EMPLE
   (EMP_NO, APELLIDO, OFICIO, DIR, FECHA_ALT, 
    SALARIO, COMISION, DEPT_NO)
 Values
   (7369, 'SANCHEZ', 'EMPLEADO', 7788, TO_DATE('12/17/1980 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    1040, NULL, 20);
Insert into EMPLE
   (EMP_NO, APELLIDO, OFICIO, DIR, FECHA_ALT, 
    SALARIO, COMISION, DEPT_NO)
 Values
   (7499, 'ARROYO', 'VENDEDOR', 7698, TO_DATE('02/20/1980 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    2080, 390, 30);
Insert into EMPLE
   (EMP_NO, APELLIDO, OFICIO, DIR, FECHA_ALT, 
    SALARIO, COMISION, DEPT_NO)
 Values
   (7521, 'SALA', 'VENDEDOR', 7698, TO_DATE('02/22/1981 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    1625, 650, 30);
Insert into EMPLE
   (EMP_NO, APELLIDO, OFICIO, DIR, FECHA_ALT, 
    SALARIO, COMISION, DEPT_NO)
 Values
   (7566, 'JIMENEZ', 'DIRECTOR', 7839, TO_DATE('04/02/1981 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    3867, NULL, 20);
Insert into EMPLE
   (EMP_NO, APELLIDO, OFICIO, DIR, FECHA_ALT, 
    SALARIO, COMISION, DEPT_NO)
 Values
   (7654, 'MARTIN', 'VENDEDOR', 7698, TO_DATE('09/29/1981 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    1625, 1820, 30);
Insert into EMPLE
   (EMP_NO, APELLIDO, OFICIO, DIR, FECHA_ALT, 
    SALARIO, COMISION, DEPT_NO)
 Values
   (7698, 'NEGRO', 'DIRECTOR', 7839, TO_DATE('05/01/1981 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    3705, NULL, 30);
Insert into EMPLE
   (EMP_NO, APELLIDO, OFICIO, DIR, FECHA_ALT, 
    SALARIO, COMISION, DEPT_NO)
 Values
   (7782, 'CEREZO', 'DIRECTOR', 7839, TO_DATE('06/09/1981 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    3185, NULL, 10);
Insert into EMPLE
   (EMP_NO, APELLIDO, OFICIO, DIR, FECHA_ALT, 
    SALARIO, COMISION, DEPT_NO)
 Values
   (7788, 'GIL', 'ANALISTA', 7566, TO_DATE('11/09/1981 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    3900, NULL, 20);
Insert into EMPLE
   (EMP_NO, APELLIDO, OFICIO, DIR, FECHA_ALT, 
    SALARIO, COMISION, DEPT_NO)
 Values
   (7839, 'REY', 'PRESIDENTE', NULL, TO_DATE('11/17/1981 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    6500, NULL, 10);
Insert into EMPLE
   (EMP_NO, APELLIDO, OFICIO, DIR, FECHA_ALT, 
    SALARIO, COMISION, DEPT_NO)
 Values
   (7844, 'TOVAR', 'VENDEDOR', 7698, TO_DATE('09/08/1981 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    1950, 0, 30);
Insert into EMPLE
   (EMP_NO, APELLIDO, OFICIO, DIR, FECHA_ALT, 
    SALARIO, COMISION, DEPT_NO)
 Values
   (7876, 'ALONSO', 'EMPLEADO', 7788, TO_DATE('09/23/1981 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    1430, NULL, 20);
Insert into EMPLE
   (EMP_NO, APELLIDO, OFICIO, DIR, FECHA_ALT, 
    SALARIO, COMISION, DEPT_NO)
 Values
   (7900, 'JIMENO', 'EMPLEADO', 7698, TO_DATE('12/03/1981 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    1235, NULL, 30);
Insert into EMPLE
   (EMP_NO, APELLIDO, OFICIO, DIR, FECHA_ALT, 
    SALARIO, COMISION, DEPT_NO)
 Values
   (7902, 'FERNANDEZ', 'ANALISTA', 7566, TO_DATE('12/03/1981 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    3900, NULL, 20);
Insert into EMPLE
   (EMP_NO, APELLIDO, OFICIO, DIR, FECHA_ALT, 
    SALARIO, COMISION, DEPT_NO)
 Values
   (7934, 'MUÑOZ', 'EMPLEADO', 7782, TO_DATE('01/23/1982 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    1690, NULL, 10);
COMMIT;

Insert into LIBRERIA
   (TEMA, ESTANTE, num_ejemplares)
 Values
   ('Informática', 'A', 15);
Insert into LIBRERIA
   (TEMA, ESTANTE, num_ejemplares)
 Values
   ('Economía', 'A', 10);
Insert into LIBRERIA
   (TEMA, ESTANTE, num_ejemplares)
 Values
   ('Deportes', 'B', 8);
Insert into LIBRERIA
   (TEMA, ESTANTE, num_ejemplares)
 Values
   ('Filosofía', 'C', 7);
Insert into LIBRERIA
   (TEMA, ESTANTE, num_ejemplares)
 Values
   ('Dibujo', 'C', 10);
Insert into LIBRERIA
   (TEMA, ESTANTE, num_ejemplares)
 Values
   ('Medicina', 'C', 16);
Insert into LIBRERIA
   (TEMA, ESTANTE, num_ejemplares)
 Values
   ('Biología', 'A', 11);
Insert into LIBRERIA
   (TEMA, ESTANTE, num_ejemplares)
 Values
   ('Geología', 'D', 7);
Insert into LIBRERIA
   (TEMA, ESTANTE, num_ejemplares)
 Values
   ('Sociedad', 'D', 9);
Insert into LIBRERIA
   (TEMA, ESTANTE, num_ejemplares)
 Values
   ('Labores', 'B', 20);
Insert into LIBRERIA
   (TEMA, ESTANTE, num_ejemplares)
 Values
   ('Jardinería', 'E', 6);
COMMIT;

Insert into NOTAS
   (DNI, COD, NOTA)
 Values
   ('12344345', 1, 6);
Insert into NOTAS
   (DNI, COD, NOTA)
 Values
   ('12344345', 2, 5);
Insert into NOTAS
   (DNI, COD, NOTA)
 Values
   ('12344345', 3, 6);
Insert into NOTAS
   (DNI, COD, NOTA)
 Values
   ('4448242', 4, 6);
Insert into NOTAS
   (DNI, COD, NOTA)
 Values
   ('4448242', 5, 8);
Insert into NOTAS
   (DNI, COD, NOTA)
 Values
   ('4448242', 6, 4);
Insert into NOTAS
   (DNI, COD, NOTA)
 Values
   ('4448242', 7, 5);
Insert into NOTAS
   (DNI, COD, NOTA)
 Values
   ('56882942', 4, 8);
Insert into NOTAS
   (DNI, COD, NOTA)
 Values
   ('56882942', 5, 7);
Insert into NOTAS
   (DNI, COD, NOTA)
 Values
   ('56882942', 6, 8);
Insert into NOTAS
   (DNI, COD, NOTA)
 Values
   ('56882942', 7, 9);
COMMIT;


REM ********** TABLA MISTEXTOS: *************

DROP TABLE MISTEXTOS cascade constraints; 

CREATE TABLE MISTEXTOS (
 TITULO  VARCHAR2(32),
 AUTOR   VARCHAR2(22),
 EDITORIAL VARCHAR2(15), 
 PAGINA  NUMBER(3)
 ) ;

INSERT INTO MISTEXTOS VALUES ('METODOLOGÍA DE LA PROGRAMACIÓN', 
'ALCALDE, GARCÍA', 'MCGRAWHILL',140);
INSERT INTO MISTEXTOS VALUES ('"INFORMÁTICA BÁSICA."', 'GARCÍA GARCERÁN', 'PARANINFO',130);
INSERT INTO MISTEXTOS VALUES ('SISTEMAS OPERATIVOS', 'J.F. GARCÍA', 'OBSBORNE',300);
INSERT INTO MISTEXTOS VALUES ('SISTEMAS DIGITALES.', 'M.A. RUÍZ', 
'PRENTICE HALL',190);
INSERT INTO MISTEXTOS VALUES ('"MANUAL DE C."', 'M.A. RUÍZ', 'MCGRAWHILL',340);

COMMIT;

REM ********** TABLA NACIMIENTOS:******************

DROP TABLE NACIMIENTOS cascade constraints; 

ALTER SESSION SET NLS_DATE_FORMAT='DD/MM/YYYY';

CREATE TABLE NACIMIENTOS (
 NOMBRE CHAR(15),
 APELLIDO CHAR(15),
 FECHANAC DATE,
 EDAD NUMBER
 );


INSERT INTO NACIMIENTOS VALUES ('PEDRO', 'SÁNCHEZ','12/05/1982', 17);
INSERT INTO NACIMIENTOS VALUES ('JUAN', 'JIMÉNEZ','23/08/1982', 17);
INSERT INTO NACIMIENTOS VALUES ('MARÍA', 'LÓPEZ','02/02/1983', 16);
INSERT INTO NACIMIENTOS VALUES ('CLARA', 'LASECA','20/05/1985', 14);
COMMIT;

REM *********** INSERTING into LIBROS  ***********

DROP TABLE "LIBROS";
CREATE TABLE "LIBROS" 
   (	"AUTOR" VARCHAR2(50 CHAR)
   ) ;
 

Insert into LIBROS (AUTOR) values ('CELA, CAMILO JOSE');
Insert into LIBROS (AUTOR) values ('GORDIMER, NADINE');
Insert into LIBROS (AUTOR) values ('G. DELGADO, FERNANDO');
Insert into LIBROS (AUTOR) values ('MARSE, JUAN');
Insert into LIBROS (AUTOR) values ('TORRENTE B., GONZALO');
