CREATE TABLE ALUMNOS  
( 
  NUM_MATRICULA NUMBER , 
  NOM_ALUMNO VARCHAR2(20)  
); 
 
CREATE TABLE PROFESORES  
( 
  ID_PROFESOR NUMBER(4) , 
  NOM_PROFESOR VARCHAR2(20)  
); 
 
CREATE TABLE MODULOS  
( 
  ID_MODULO VARCHAR2(3) , 
  NOM_MODULO VARCHAR2(20) , 
  ID_PROFESOR NUMBER(4)  
); 
 
CREATE TABLE MATRICULA  
( 
  NUM_MATRICULA NUMBER(4) , 
  ID_MODULO VARCHAR2(3) , 
  NOTA NUMBER(4, 2)  
);